import base64
import uuid
from typing import Dict, List

from openai import OpenAI


class MultimodalRAGEngine:
    """
    Multimodal RAG engine using dual-representation indexing.

    Visual assets are:
    1. Summarized by a vision-capable LLM.
    2. Stored as raw base64 data in a document store.
    3. Represented in a searchable in-memory vector index
       through their textual summaries.

    The retrieved parent visual asset can then be passed
    directly to the multimodal generation model.
    """

    def __init__(self, api_key: str):
        self.client = OpenAI(api_key=api_key)

        # Stores the original visual assets.
        self.docstore: Dict[str, Dict] = {}

        # Stores searchable textual representations.
        self.vector_index: List[Dict] = []

    @staticmethod
    def _encode_image_b64(image_bytes: bytes) -> str:
        """
        Convert image bytes into a Base64 string.
        """

        return base64.b64encode(image_bytes).decode("utf-8")

    def summarize_visual_element(
        self,
        image_bytes: bytes,
        element_type: str = "chart",
    ) -> str:
        """
        Generate a searchable textual summary of a visual element.

        Args:
            image_bytes: Raw image bytes.
            element_type: Type of visual element such as
                chart, table, or diagram.

        Returns:
            Textual semantic description generated by the vision model.
        """

        b64_img = self._encode_image_b64(image_bytes)

        prompt = (
            f"Analyze this {element_type}. "
            "Detail all important data points, trends, "
            "relationships, columns, labels, and structural "
            "information so the description can be used for "
            "dense semantic retrieval."
        )

        response = self.client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt,
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": (
                                    "data:image/png;base64,"
                                    f"{b64_img}"
                                )
                            },
                        },
                    ],
                }
            ],
            max_tokens=500,
        )

        return response.choices[0].message.content

    def ingest_image_element(
        self,
        image_bytes: bytes,
        element_type: str = "chart",
    ) -> str:
        """
        Ingest a visual element using dual representation.

        The original image is stored in the document store,
        while its vision-generated textual summary is stored
        in the searchable index.

        Returns:
            Unique document identifier.
        """

        doc_id = str(uuid.uuid4())

        summary = self.summarize_visual_element(
            image_bytes=image_bytes,
            element_type=element_type,
        )

        self.docstore[doc_id] = {
            "type": "image",
            "element_type": element_type,
            "b64": self._encode_image_b64(image_bytes),
        }

        self.vector_index.append(
            {
                "doc_id": doc_id,
                "summary": summary,
                "element_type": element_type,
            }
        )

        return doc_id

    def query_multimodal(
        self,
        user_query: str,
    ) -> str:
        """
        Answer a query using the retrieved visual context.

        The current implementation uses the first indexed
        visual element as the retrieved parent asset.

        Returns:
            LLM-generated answer based on visual context.
        """

        if not self.vector_index:
            raise ValueError(
                "No visual elements have been indexed."
            )

        matched_doc_id = self.vector_index[0]["doc_id"]

        raw_asset = self.docstore[matched_doc_id]

        response = self.client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": (
                                "Answer the following query "
                                "using the provided visual context:\n\n"
                                f"{user_query}"
                            ),
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": (
                                    "data:image/png;base64,"
                                    f"{raw_asset['b64']}"
                                )
                            },
                        },
                    ],
                }
            ],
        )

        return response.choices[0].message.content
